kind: Pod
apiVersion: v1
metadata:
  name: redis
  labels:
    name: redis
    role: master
    visualize: "true"
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - name: redis-server
          containerPort: 6379
