kind: Service
apiVersion: v1
metadata:
  name: redis
  labels:
    name: redis
    role: master
    visualize: "true"
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis
    role: master
  type: LoadBalancer
